---
- hosts: localhost
  become: yes
  vars_files:
   - vars.yml
  tasks:
    - name: install software
      yum:
        name: "{{ item }}"
        state: absent
      loop:
        - nifi
        - mariadb
    - name: check services
      service:
        name: "{{ item }}"
        state: started
      loop: "{{ services_list }}"
