--- # playbook with variables
- hosts: localhost
  tasks:
    - name: create working directory
      file:
        name: "{{ working_dir }}"
        state: directory
    - name: write services list
      lineinfile:
        path: "{{ working_dir }}/services.txt"
        create: yes
        line: "{{ services_list }}"
    - name: view share property
      command: ls -la "{{ share_paths['nfs'] }}"
      register: cmd_output
    - name: copy comand output to file
      copy:
        content: "{{ cmd_output }}"
        dest: "{{ working_dir }}/cmd_output.txt"


